version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    restart: always
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/officer_cv
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=officer_cv
    ports:
      - "5432:5432"

  angular-app:
    build:
      context: ../noc-officer-cv-ui
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "80:80"
    restart: always