# File Upload
file.photo-max-size=5242880
file.file-max-size=5242880
file.upload-dir=/var/www/employee_cv/photos/
file.photo-dir=/var/www/employee_cv/files/
app.cors.allowed-origins=https://biography.interior.gov.kh,http://localhost:4200
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/biography
spring.datasource.username=postgres
spring.datasource.password=root
# Use validate in prod, update only in dev
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.datasource.hikari.auto-commit=false