file.upload-dir=C:/Users/MOI-NOC/Hosting/Server/files/
file.photo-dir=C:/Users/MOI-NOC/Hosting/Server/photos/
file.signature-dir=C:/Users/MOI-NOC/Hosting/Server/signatures/
logging.file.name=C:/Users/MOI-NOC/Hosting/Server/logs/application.log

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
