# File Upload
file.photo-max-size=5242880
file.file-max-size=5242880
file.upload-dir=upload/photos/
file.photo-dir=upload/files/
app.cors.allowed-origins=http//n4-police-profile.interior.gov.kh
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/n4polpro
spring.datasource.username=n4polpro
spring.datasource.password=Moi@PoliceP!@#123
# Use validate in prod, update only in dev
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.datasource.hikari.auto-commit=false