CREATE TABLE IF NOT EXISTS permissions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id INTEGER NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    permission_id INTEGER NOT NULL REFERENCES permissions (id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id INTEGER NOT NULL REFERENCES _user (id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

INSERT INTO permissions (name, description)
VALUES
    ('EMPLOYEE_CV_READ', 'Read employee CV records and dashboard statistics'),
    ('EMPLOYEE_CV_CREATE', 'Create employee CV records'),
    ('EMPLOYEE_CV_UPDATE', 'Update employee CV records'),
    ('EMPLOYEE_CV_DELETE', 'Delete employee CV records'),
    ('USER_ACCOUNT_MANAGE', 'Manage user account status, password, profile, and department'),
    ('ORGANIZATION_MANAGE', 'Manage departments, bureaus, positions, skills, and address lookup data')
ON CONFLICT (name) DO UPDATE
SET description = EXCLUDED.description;

INSERT INTO roles (name)
VALUES
    ('ADMIN'),
    ('MANAGER'),
    ('USER'),
    ('HEAD_OF_BUREAU')
ON CONFLICT (name) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name IN (
    'EMPLOYEE_CV_READ',
    'EMPLOYEE_CV_CREATE',
    'EMPLOYEE_CV_UPDATE',
    'EMPLOYEE_CV_DELETE',
    'USER_ACCOUNT_MANAGE',
    'ORGANIZATION_MANAGE'
)
WHERE r.name = 'ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name IN (
    'EMPLOYEE_CV_READ',
    'EMPLOYEE_CV_CREATE',
    'EMPLOYEE_CV_UPDATE'
)
WHERE r.name = 'MANAGER'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name IN (
    'EMPLOYEE_CV_READ',
    'EMPLOYEE_CV_UPDATE'
)
WHERE r.name = 'HEAD_OF_BUREAU'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name = 'EMPLOYEE_CV_READ'
WHERE r.name = 'USER'
ON CONFLICT DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM _user u
JOIN roles r ON r.name = u.role
WHERE u.role IS NOT NULL
ON CONFLICT DO NOTHING;
